name: KeepXP
version: 0.1.0
description: Keeps player XP on death
author: acomputerdog
main: net.acomputerdog.keepxp.PluginKeepXP

perimssions:
  keepxp.keep:
    description: If true the player will keep XP on death
    default: true